spring:
  config:
    import:
      - classpath:META-INF/config/modules/kafka/apims-kafka-base.yml
---
spring:
  config:
    activate:
      on-profile: unit-test
    import:
      - classpath:META-INF/config/env/unit-test.yml

---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - classpath:META-INF/config/env/dev.yml
